### ISSUE TITLE
Failed config

### ISSUE THREAD

**Issue by Spp595** [jdillenburg/esphome#1]
Component sensor.adxl345 cannot be loaded via YAML (no CONFIG_SCHEMA).
  platform: adxl345
  id: my_adxl345
  accel_x: 
    name: Acceleration X
  accel_y: 
    name: Acceleration Y
  accel_z: 
    name: Acceleration Z

I use external_components to include the library

**Comment by jdillenburg** [comment]
You need to use adxl345 at the top level of the yaml and not with the platform field of a sensor.  See my bed_controller2.yaml for an example usage:

adxl345:
  id: adxl345_sensor
  address: 0x53
  update_interval: 100ms
  off_vertical:
    id: bed_angle
    name: "Bed Angle"
    unit_of_measurement: degrees
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
      - throttle_average: 10s
    on_value:
      then:
        - lambda: |-
            id(bed_position).publish_state(100 * (id(bed_angle).state - id(bed_lower_limit).state) / (id(bed_upper_limit).state - id(bed_lower_limit).state));
        - script.execute: start_motor_if_needed

**Comment by jdillenburg** [comment]
I see my docs are messed up.  I'll fix that.  There is no platform: adxl345.  Try this:

```
esphome:
  name: adxl345
  libraries:
  - "Wire"
  - "SPI"
  - "Adafruit BusIO"
  - "Adafruit Unified Sensor"
  - "Adafruit ADXL345"
 
esp8266:
  board: esp01_1m

wifi:
  ssid: my network
  password: my password

api:

i2c:
  sda: GPIO2
  scl: GPIO0
  frequency: 400kHz

# Define component
adxl345:
  - id: my_adxl345
    address: 0x53
    update_interval: 100ms
    accel_x:
      name: "Acceleration X"
    accel_y:
      name: "Acceleration Y"
    accel_z:
      name: "Acceleration Z"

external_components:
  - source:
      type: git
      url: https://github.com/jdillenburg/esphome
      ref: main
    components: [ adxl345 ]
```
